variables:
  DOCKER_DRIVER: overlay2
  RELEASE_IMAGE: registry.gitlab.com/islandoftex/images/texlive
stages:
  - baseimage
  - iso
  - build
  - test

.buildtemplate: &builddefinition
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker info

.testtemplate: &testdefinition
  stage: test
  script:
    - arara -l -v test.tex

build:baseimage:
  stage: baseimage
  <<: *builddefinition
  script:
    - docker build -f Dockerfile.base --tag $RELEASE_IMAGE:base .
    - docker push $RELEASE_IMAGE:base

.latesttemplate: &latestdefinition
  <<: *builddefinition
  stage: build
  needs: ["build:baseimage"]
  script:
    - SUFFIX="`if [ "$DOCFILES" = "yes" ]; then echo "-doc"; fi`"
    - SUFFIX="$SUFFIX`if [ "$SRCFILES" = "yes" ]; then echo "-src"; fi`"
    - IMAGETAG="TL$CURRENTRELEASE-`date +%Y-%m-%d-%H-%M`$SUFFIX"
    - docker build -f Dockerfile.latest --tag $RELEASE_IMAGE:$IMAGETAG --tag $RELEASE_IMAGE:latest$SUFFIX --build-arg DOCFILES=$DOCFILES --build-arg SRCFILES=$SRCFILES .
    - docker push $RELEASE_IMAGE:$IMAGETAG
    - docker push $RELEASE_IMAGE:latest$SUFFIX
  only:
    variables:
      - $LATESTRELEASES == "true"

build:latest:
  variables:
    CURRENTRELEASE: 2019
    DOCFILES: "no"
    SRCFILES: "no"
  <<: *latestdefinition
test:latest:
  stage: test
  image: $RELEASE_IMAGE:latest
  needs: ["build:latest"]
  <<: *testdefinition
  only:
    variables:
      - $LATESTRELEASES == "true"
build:latest:doc:
  variables:
    CURRENTRELEASE: 2019
    DOCFILES: "yes"
    SRCFILES: "no"
  <<: *latestdefinition
build:latest:src:
  variables:
    CURRENTRELEASE: 2019
    DOCFILES: "no"
    SRCFILES: "yes"
  <<: *latestdefinition
build:latest:docsrc:
  variables:
    CURRENTRELEASE: 2019
    DOCFILES: "yes"
    SRCFILES: "yes"
  <<: *latestdefinition

.isotemplate: &isodefinition
  <<: *builddefinition
  stage: iso
  script:
    - IMAGETAG="TL$CURRENTRELEASE-historic-iso"
    - if [ -z "$ISONAME" ]; then export ISONAME=texlive.iso; fi
    - docker build -f Dockerfile.iso --tag $RELEASE_IMAGE:$IMAGETAG --build-arg CURRENTRELEASE=$CURRENTRELEASE --build-arg ISONAME=$ISONAME .
    - docker push $RELEASE_IMAGE:$IMAGETAG
  only:
    variables:
      - $HISTORICALRELEASES == "true"

.historictemplate: &historicdefinition
  <<: *builddefinition
  stage: build
  script:
    - SUFFIX="`if [ "$DOCFILES" = "yes" ]; then echo "-doc"; fi`"
    - SUFFIX="$SUFFIX`if [ "$SRCFILES" = "yes" ]; then echo "-src"; fi`"
    - IMAGETAG="TL$CURRENTRELEASE-historic$SUFFIX"
    - docker build -f Dockerfile.historic --tag $RELEASE_IMAGE:$IMAGETAG --build-arg CURRENTRELEASE=$CURRENTRELEASE --build-arg DOCFILES=$DOCFILES --build-arg SRCFILES=$SRCFILES .
    - docker push $RELEASE_IMAGE:$IMAGETAG
  only:
    variables:
      - $HISTORICALRELEASES == "true"

build:iso:2018:
  variables:
    CURRENTRELEASE: 2018
  <<: *isodefinition
build:historic:2018:
  needs: ["build:iso:2018"]
  variables:
    CURRENTRELEASE: 2018
    DOCFILES: "no"
    SRCFILES: "no"
  <<: *historicdefinition
test:historic:2018:
  image: $RELEASE_IMAGE:TL2018-historic
  <<: *testdefinition
  only:
    variables:
      - $HISTORICALRELEASES == "true"
build:historic:2018-doc:
  needs: ["build:iso:2018"]
  variables:
    CURRENTRELEASE: 2018
    DOCFILES: "yes"
    SRCFILES: "no"
  <<: *historicdefinition
build:historic:2018-src:
  needs: ["build:iso:2018"]
  variables:
    CURRENTRELEASE: 2018
    DOCFILES: "no"
    SRCFILES: "yes"
  <<: *historicdefinition
build:historic:2018-doc-src:
  needs: ["build:iso:2018"]
  variables:
    CURRENTRELEASE: 2018
    DOCFILES: "yes"
    SRCFILES: "yes"
  <<: *historicdefinition
build:iso:2017:
  variables:
    CURRENTRELEASE: 2017
  <<: *isodefinition
build:historic:2017:
  needs: ["build:iso:2017"]
  variables:
    CURRENTRELEASE: 2017
    DOCFILES: "no"
    SRCFILES: "no"
  <<: *historicdefinition
test:historic:2017:
  image: $RELEASE_IMAGE:TL2017-historic
  <<: *testdefinition
  only:
    variables:
      - $HISTORICALRELEASES == "true"
build:historic:2017-doc:
  needs: ["build:iso:2017"]
  variables:
    CURRENTRELEASE: 2017
    DOCFILES: "yes"
    SRCFILES: "no"
  <<: *historicdefinition
build:historic:2017-src:
  needs: ["build:iso:2017"]
  variables:
    CURRENTRELEASE: 2017
    DOCFILES: "no"
    SRCFILES: "yes"
  <<: *historicdefinition
build:historic:2017-doc-src:
  needs: ["build:iso:2017"]
  variables:
    CURRENTRELEASE: 2017
    DOCFILES: "yes"
    SRCFILES: "yes"
  <<: *historicdefinition
build:iso:2016:
  variables:
    CURRENTRELEASE: 2016
  <<: *isodefinition
build:historic:2016:
  needs: ["build:iso:2016"]
  variables:
    CURRENTRELEASE: 2016
    DOCFILES: "no"
    SRCFILES: "no"
  <<: *historicdefinition
test:historic:2016:
  image: $RELEASE_IMAGE:TL2016-historic
  <<: *testdefinition
  only:
    variables:
      - $HISTORICALRELEASES == "true"
build:historic:2016-doc:
  needs: ["build:iso:2016"]
  variables:
    CURRENTRELEASE: 2016
    DOCFILES: "yes"
    SRCFILES: "no"
  <<: *historicdefinition
build:historic:2016-src:
  needs: ["build:iso:2016"]
  variables:
    CURRENTRELEASE: 2016
    DOCFILES: "no"
    SRCFILES: "yes"
  <<: *historicdefinition
build:historic:2016-doc-src:
  needs: ["build:iso:2016"]
  variables:
    CURRENTRELEASE: 2016
    DOCFILES: "yes"
    SRCFILES: "yes"
  <<: *historicdefinition
build:iso:2015:
  variables:
    CURRENTRELEASE: 2015
  <<: *isodefinition
build:historic:2015:
  needs: ["build:iso:2015"]
  variables:
    CURRENTRELEASE: 2015
    DOCFILES: "no"
    SRCFILES: "no"
  <<: *historicdefinition
test:historic:2015:
  image: $RELEASE_IMAGE:TL2015-historic
  <<: *testdefinition
  only:
    variables:
      - $HISTORICALRELEASES == "true"
build:historic:2015-doc:
  needs: ["build:iso:2015"]
  variables:
    CURRENTRELEASE: 2015
    DOCFILES: "yes"
    SRCFILES: "no"
  <<: *historicdefinition
build:historic:2015-src:
  needs: ["build:iso:2015"]
  variables:
    CURRENTRELEASE: 2015
    DOCFILES: "no"
    SRCFILES: "yes"
  <<: *historicdefinition
build:historic:2015-doc-src:
  needs: ["build:iso:2015"]
  variables:
    CURRENTRELEASE: 2015
    DOCFILES: "yes"
    SRCFILES: "yes"
  <<: *historicdefinition
build:iso:2014:
  variables:
    CURRENTRELEASE: 2014
  <<: *isodefinition
build:historic:2014:
  needs: ["build:iso:2014"]
  variables:
    CURRENTRELEASE: 2014
    DOCFILES: "no"
    SRCFILES: "no"
  <<: *historicdefinition
test:historic:2014:
  image: $RELEASE_IMAGE:TL2014-historic
  <<: *testdefinition
  only:
    variables:
      - $HISTORICALRELEASES == "true"
build:historic:2014-doc:
  needs: ["build:iso:2014"]
  variables:
    CURRENTRELEASE: 2014
    DOCFILES: "yes"
    SRCFILES: "no"
  <<: *historicdefinition
build:historic:2014-src:
  needs: ["build:iso:2014"]
  variables:
    CURRENTRELEASE: 2014
    DOCFILES: "no"
    SRCFILES: "yes"
  <<: *historicdefinition
build:historic:2014-doc-src:
  needs: ["build:iso:2014"]
  variables:
    CURRENTRELEASE: 2014
    DOCFILES: "yes"
    SRCFILES: "yes"
  <<: *historicdefinition

.build:iso:2013:
  variables:
    CURRENTRELEASE: 2013
    ISONAME: "texlive2013.iso"
  <<: *isodefinition
.build:iso:2012:
  variables:
    CURRENTRELEASE: 2012
    ISONAME: "texlive2012.iso"
  <<: *isodefinition
.build:iso:2011:
  variables:
    CURRENTRELEASE: 2011
    ISONAME: "texlive2011.iso"
  <<: *isodefinition
.build:iso:2010:
  variables:
    CURRENTRELEASE: 2010
    ISONAME: "texlive2010.iso"
  <<: *isodefinition
.build:iso:2009:
  variables:
    CURRENTRELEASE: 2009
    ISONAME: "texlive2009.iso"
  <<: *isodefinition
.build:iso:2008:
  variables:
    CURRENTRELEASE: 2008
    ISONAME: "texlive2008.iso"
  <<: *isodefinition
