variables:
  DOCKER_DRIVER: overlay2
  RELEASE_IMAGE: registry.gitlab.com/islandoftex/images/texlive
stages:
  - baseimage
  - iso
  - build
  - test

.buildtemplate:
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN registry.gitlab.com
    - docker info

.testtemplate:
  stage: test
  script:
    - arara -l -v test.tex

build:baseimage:
  stage: baseimage
  extends: .buildtemplate
  script:
    - docker build -f Dockerfile.base --tag $RELEASE_IMAGE:base .
    - docker push $RELEASE_IMAGE:base

.latestruletemplate:
  rules:
    - if: '$LATESTRELEASES == "true"'
      when: always
    - when: never
.historicalruletemplate:
  rules:
    - if: '$HISTORICALRELEASES == "true"'
      when: always
    - when: never

.latesttemplate:
  extends: [.buildtemplate, .latestruletemplate]
  stage: build
  needs: ["build:baseimage"]
  script:
    - SUFFIX="`if [ "$DOCFILES" = "yes" ]; then echo "-doc"; fi`"
    - SUFFIX="$SUFFIX`if [ "$SRCFILES" = "yes" ]; then echo "-src"; fi`"
    - IMAGETAG="TL$CURRENTRELEASE-`date +%Y-%m-%d-%H-%M`$SUFFIX"
    - docker build -f Dockerfile.latest --tag $RELEASE_IMAGE:$IMAGETAG --tag $RELEASE_IMAGE:latest$SUFFIX --build-arg DOCFILES=$DOCFILES --build-arg SRCFILES=$SRCFILES .
    - docker push $RELEASE_IMAGE:$IMAGETAG
    - docker push $RELEASE_IMAGE:latest$SUFFIX

.isotemplate:
  extends: [.buildtemplate, .historicalruletemplate]
  stage: iso
  script:
    - IMAGETAG="TL$CURRENTRELEASE-historic-iso"
    - if [ -z "$ISONAME" ]; then export ISONAME=texlive.iso; fi
    - docker build -f Dockerfile.iso --tag $RELEASE_IMAGE:$IMAGETAG --build-arg CURRENTRELEASE=$CURRENTRELEASE --build-arg ISONAME=$ISONAME .
    - docker push $RELEASE_IMAGE:$IMAGETAG

.historictemplate:
  extends: [.buildtemplate, .historicalruletemplate]
  stage: build
  script:
    - SUFFIX="`if [ "$DOCFILES" = "yes" ]; then echo "-doc"; fi`"
    - SUFFIX="$SUFFIX`if [ "$SRCFILES" = "yes" ]; then echo "-src"; fi`"
    - IMAGETAG="TL$CURRENTRELEASE-historic$SUFFIX"
    - docker build -f Dockerfile.historic --tag $RELEASE_IMAGE:$IMAGETAG --build-arg CURRENTRELEASE=$CURRENTRELEASE --build-arg DOCFILES=$DOCFILES --build-arg SRCFILES=$SRCFILES .
    - docker push $RELEASE_IMAGE:$IMAGETAG

# build the latest image
build:latest:
  extends: .latesttemplate
  parallel:
    matrix:
      - CURRENTRELEASE: [2020]
        DOCFILES: ["yes", "no"]
        SRCFILES: ["yes", "no"]
test:latest:
  image: $RELEASE_IMAGE:latest
  needs: ["build:latest"]
  extends: [.testtemplate, .latestruletemplate]

# NOTE: historic images have to be built in batches (because the server has a rate
#       limit which we should obey to get the CI passing)
# build historic images between 2018 and 2019 (inclusive)
build:iso:18to19:
  extends: .isotemplate
  parallel:
    matrix:
      - CURRENTRELEASE: [2018, 2019]
        ISOBUILD: "true" # this is a dummy parameter to make the matrix run the list
build:historic:18to19:
  extends: .historictemplate
  parallel:
    matrix:
      - CURRENTRELEASE: [2018, 2019]
        DOCFILES: ["yes", "no"]
        SRCFILES: ["yes", "no"]

# build historic images between 2014 and 2017 (inclusive)
build:iso:14to17:
  extends: .isotemplate
  parallel:
    matrix:
      - CURRENTRELEASE: [2014, 2015, 2016, 2017]
        ISOBUILD: "true" # this is a dummy parameter to make the matrix run the list
build:historic:14to17:
  extends: .historictemplate
  parallel:
    matrix:
      - CURRENTRELEASE: [2014, 2015, 2016, 2017]
        DOCFILES: ["yes", "no"]
        SRCFILES: ["yes", "no"]

# test all previously built historic releases by running our test definition
test:historic:
  image: $RELEASE_IMAGE:TL$CURRENTRELEASE-historic
  extends: [.testtemplate, .historicalruletemplate]
  parallel:
    matrix:
      - CURRENTRELEASE: [2014, 2015, 2016, 2017, 2018, 2019]
        TESTBUILD: "true" # this is a dummy parameter to make the matrix run the list

# currently, we do not build these but 2008–2013 require us to set the ISONAME
# so this is included as an example
.build:prehistoric-iso:
  extends: .isotemplate
  variables:
    ISONAME: texlive$CURRENTRELEASE.iso
  parallel:
    matrix:
      - CURRENTRELEASE: [2008, 2009, 2010, 2011, 2012, 2013]
        ISOBUILD: "true" # this is a dummy parameter to make the matrix run the list
