repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-merge-conflict
  - id: check-symlinks
  - id: destroyed-symlinks
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://github.com/Lucas-C/pre-commit-hooks
  rev: v1.3.0
  hooks:
  - id: forbid-crlf
  - id: remove-crlf
  - id: forbid-tabs
  - id: remove-tabs
- repo: https://github.com/hadolint/hadolint
  rev: v2.10.0
  hooks:
  - id: hadolint
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 3.0.0
  hooks:
    - id: forbid-binary
    - id: git-check
    - id: shellcheck
    - id: shfmt
      args: ['-i 2']
- repo: https://github.com/nix-community/nixpkgs-fmt
  rev: v1.3.0
  hooks:
  - id: nixpkgs-fmt
