name: Publish Docker Images

on:
  schedule:
    # run on 1th and 15th of each month
    - cron: '1 2 1,15 * *'
  push:
    branches:
      - main
      - ghactionstest
    tags:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-base:
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      image: base
      dockerfile: Dockerfile.base
  build-texlive:
    needs:
      - build-base
    uses: ./.github/workflows/build-docker.yml
    secrets: inherit
    permissions:
      contents: read
      packages: write
    with:
      base: ${{ needs.build-base.outputs.reference }}
      image: texlive
      dockerfile: Dockerfile
        
